### ISSUE TITLE
Can this work with areas?

### ISSUE THREAD

**Issue by JulienPalard** [cphyc/matplotlib-label-lines#76]
I'm trying to label areas, like here: https://github.com/JulienPalard/python-versions/blob/8aa82b48375f4771476fc821b0e8495d958173bb/python-versions.py#L161

It does not appear to work, I tried:

```python
    to_plot.plot.area(stacked=True, figsize=(10, 10 * 2 / 3))
    labelLines(plt.gca().get_lines())
    plt.savefig("python-versions-pct.png")
```

And I'm getting:

```pytb
Traceback (most recent call last):
  File "/home/mdk/clones/JulienPalard/python-versions/python-versions.py", line 170, in <module>
    plot_pct()
  File "/home/mdk/clones/JulienPalard/python-versions/python-versions.py", line 163, in plot_pct
    labelLines(plt.gca().get_lines())
  File "/home/mdk/.local/lib/python3.9/site-packages/labellines/core.py", line 222, in labelLines
    xdata = ensure_float(line.get_xdata())
AttributeError: 'PolyCollection' object has no attribute 'get_xdata'
```

**Comment by cphyc** [comment]
Closing this due to the lack of activity. If anyone is interested in implementing I would be happy to integrate such a change.
