### ISSUE TITLE
Stopped working for axes containing errorbars

### ISSUE THREAD

**Issue by elfehr** [cphyc/matplotlib-label-lines#84]
I don't remember if I had a recent update, but a function where I'm labeling errorbars suddenly stopped working without any change on my part, whereas it works fine when if change the errorbar into a simple plot.
I have matplotlib-label-lines 0.4.3, matplotlib 3.5.1, numpy 1.22.1.

It gives the following error:
```
File "/home/x/Documents/Paper/images/plot_functions.py", line 470, in polarization
    labelLines(ax.get_lines())
  File "/home/x/Documents/Paper/.virtualenv/lib/python3.10/site-packages/labellines/core.py", line 276, in labelLines
    labelLine(
  File "/home/x/Documents/Paper/.virtualenv/lib/python3.10/site-packages/labellines/core.py", line 58, in labelLine
    mask = np.isfinite(ydata)
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

It also gives the same error if there is any errorbar on the axes even if that's not the one I'm trying to label. 
I tracked down that the dtype of `ax.get_lines().get_ydata()` is an object instead of being a float for errorbars, and it worked again when modified core.py to I convert the object into a float:
```
ydata = line.get_ydata()
ydata = np.array(ydata, dtype=float)
mask = np.isfinite(ydata)
```

**Comment by elfehr** [comment]
I suspect it's related: labellines clips xval in the allowed range for the errorbars when the value I give is already supposed to be in the allowed range.

```
/home/x/Documents/Paper/.virtualenv/lib/python3.10/site-packages/labellines/core.py:253:
UserWarning: The value at position 0 in `xvals` is outside the range of its associated line (xmin=-4.62962962963426e-11, xmax=4.6296296296296294e-11, xval=3.5). Clipping it into the allowed range.
```

The x axis of the errorbars definitely contain 3.5:
```
[-4.0, -3.9, -3.8000000000000003, -3.7, -3.6, -3.5, -3.4, -3.3000000000000003, -3.2, -3.1, -3.0, -2.9, -2.8000000000000003, -2.7, -2.6, -2.5, -2.4, -2.3000000000000003, -2.2, -2.1, -2.0, -1.9000000000000001, -1.8, -1.7, -1.6, -1.5, -1.4000000000000001, -1.3, -1.2, -1.1, -1.0, -0.9, -0.8, -0.7000000000000001, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1, 0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7000000000000001, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4000000000000001, 1.5, 1.6, 1.7, 1.8, 1.9000000000000001, 2.0, 2.1, 2.2, 2.3000000000000003, 2.4, 2.5, 2.6, 2.7, 2.8000000000000003, 2.9, 3.0, 3.1, 3.2, 3.3000000000000003, 3.4, 3.5, 3.6, 3.7, 3.8000000000000003, 3.9, 4.0]
```

But `xdata = ensure_float(line.get_xdata())` in core.py returns other values:

```
[-4.62962963e-11 -3.47222222e-11 -3.47222222e-11 -3.47222222e-11
 -3.47222222e-11 -3.47222222e-11 -3.47222222e-11 -3.47222222e-11
 -3.47222222e-11 -3.47222222e-11 -3.47222222e-11 -2.31481481e-11
 -2.31481481e-11 -2.31481481e-11 -2.31481481e-11 -2.31481481e-11
 -2.31481481e-11 -2.31481481e-11 -2.31481481e-11 -2.31481481e-11
 -2.31481481e-11 -1.15740741e-11 -1.15740741e-11 -1.15740741e-11
 -1.15740741e-11 -1.15740741e-11 -1.15740741e-11 -1.15740741e-11
 -1.15740741e-11 -1.15740741e-11 -1.15740741e-11  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  1.15740741e-11  1.15740741e-11
  1.15740741e-11  1.15740741e-11  1.15740741e-11  1.15740741e-11
  1.15740741e-11  1.15740741e-11  1.15740741e-11  1.15740741e-11
  2.31481481e-11  2.31481481e-11  2.31481481e-11  2.31481481e-11
  2.31481481e-11  2.31481481e-11  2.31481481e-11  2.31481481e-11
  2.31481481e-11  2.31481481e-11  3.47222222e-11  3.47222222e-11
  3.47222222e-11  3.47222222e-11  3.47222222e-11  3.47222222e-11
  3.47222222e-11  3.47222222e-11  3.47222222e-11  3.47222222e-11
  4.62962963e-11]
```

This is also solved by modifying core.py because for some reason `ensure_float` is giving the wrong values.

Change needed both line 251 and 54:
```
# xdata = ensure_float(line.get_xdata())
xdata = np.array(line.get_xdata(), dtype=float)
```

After that, the label for the errorbar plot works fine again, and as far as I can see it didn't break the labels of the other types of plots.

**Comment by cphyc** [comment]
@elfehr would you mind testing #85 and tell me if this fixes your issue?

**Comment by elfehr** [comment]
Thanks for working on that! But sadly no, both problems are still here:

```
/home/x/Documents/Paper/.virtualenv/lib/python3.10/site-packages/labellines/core.py:252: UserWarning: The value at position 1 in `xvals` is outside the range of its associated line (xmin=-4.62962962963426e-11, xmax=4.6296296296296294e-11, xval=-3.5). Clipping it into the allowed range.
  warnings.warn(
Traceback (most recent call last):
  File "/home/x/Documents/Paper/images/plot_functions.py", line 469, in polarization
    labelLines(ax.get_lines(), zorder=10, align=False, xvals=names_pos[0], yoffsets= names_pos[1])
  File "/home/x/Documents/Paper/.virtualenv/lib/python3.10/site-packages/labellines/core.py", line 275, in labelLines
    labelLine(
  File "/home/x/Documents/Paper/.virtualenv/lib/python3.10/site-packages/labellines/core.py", line 57, in labelLine
    mask = np.isfinite(ydata)
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

**Comment by elfehr** [comment]
I figured out it each error happens when either x or y is a list and not a numpy array. But in both cases, `plt.plot(x, y)` works fine.

```
import numpy as np
import matplotlib.pyplot as plt
from labellines import labelLines

fig, ax = plt.subplots()
samples = ['a', 'b']
pos = [-1, 1]

# no error
x = np.arange(-4, 4.1, 0.1)
ys = [np.random.rand(len(x)), np.random.rand(len(x))]

# errors
x = list(np.arange(-4, 4.1, 0.1))
ys = [list(np.random.rand(len(x))), list(np.random.rand(len(x)))]

for sample, y in zip(samples, ys):
    # ax.plot(x, y, label=sample) # no error
    ax.errorbar(x, y, yerr=0.1, label=sample) # error

labelLines(ax.get_lines(), align=False, xvals=pos)
```

For x, #85 didn't work because `value.dtype == "O"` is true. I'm not sure when that happens.
For y, it seems that ydata is also an object array instead of a float array, so that's why `np.isfinite(ydata)` complains about its type.

```
line = ax.get_lines()[0]
xdata = line.get_xdata()
ydata = line.get_ydata()

x = np.array(x)
y = np.array(ys[0])

print(all(xdata == x), x.dtype, xdata.dtype)
print(all(ydata == y), y.dtype, ydata.dtype)

print(np.isfinite(y))
print(np.isfinite(ydata))
```
```
True float64 float64
True float64 object
True
Traceback (most recent call last):
  File "/home/x/Documents/Paper/images/test.py", line 34, in <module>
    print(all(np.isfinite(ydata)))
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```
